spring:
  application:
    name: StorageService
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/iam_service/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/StorageService
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
storage:
  upload_uri_pattern: yyyy-MMMM\\dd
  upload_path: file
  download-base-url: http://localhost:${server.port}/api/v1/file
server:
  port: 8086
debug: true
