spring:
  application:
    name: StorageService
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/iam_service/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/StorageService
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
storage:
  upload_path: C:\Users\241102\IdeaProjects\StorageService\src\main\resources
  download-base-url: http://localhost:${server.port}/api/v1/file
server:
  port: 8086
